### PR TITLE
follow migration guide

### PR DESCRIPTION
**Pull request by mohamberger**
hey @steffkes, maybe you can help me with the docker setup to run TinaCMS locally?

### CODE REVIEW

**Comment by steffkes** [comment]
@mohamberger can you explain a bit, what exactly doesn't work? And what you've tried? Making sure I'm tackling the issues at hand and not going down a unrelated rabbit hole I stumbled over

**Comment by mohamberger** [comment]
@steffkes 
ich bin bisher nur dem Migration Guide gefolgt. Als ich dann TinaCMS aufrufen wollte war die Seite leer oder war nicht erreichbar (kann ich mich leider nicht mehr dran erinnern). Dann hab ich versucht ein Port Mapping zum Container hinzuzufügen, dass der Port von TinaCMS auch nach Außen verfügbar ist. Leider ohne Erfolg.

Ich hab mich bisher auf jeden Fall zu wenig damit beschäftigt. Würde mir mega helfen, wenn du ausprobieren würdest, ob du das TinaCMS in einem Docker Container zum Laufen bekommst.

**Comment by steffkes** [comment]
Alright, down the rabbit hole. Understanding how TinaCMS works .. what processes it spawns and how it all works. 

Long story short: I don't have a solution (yet). What I know this far: It's based on vite, which delivers the admin single page app. But there are no hooks for the config to change the listening host for the server. Vite per default only runs on `localhost`, until you configure it otherwise:

```
# netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:43609        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      68/node
tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN      31/node
tcp6       0      0 :::9000                 :::*                    LISTEN      31/node
```

https://github.com/tinacms/tinacms/pull/3484 introduced something, which seemingly got lost since then. at least it doesn't seem to be present anymore.

**Comment by steffkes** [comment]
looking at the history for the files that the previously mentioned pull request changed: the merged a bigger refactoring at the beginning of March: https://github.com/tinacms/tinacms/pull/3659

I'll follow up there. Probably it just got reverted and therefore lost. If you search for "tinacms docker" there isn't much happening .. if they develop all locally, they wouldn't even notice

**Comment by steffkes** [comment]
With the latest changes from tinacms, it's working! http://localhost:2500/admin/ gives you the admin interface, the entire server is exposed on http://localhost:4001 - i didn't try to change the port into something in the 25xx range right away .. we should probably verify that it's working as expected.

just FYI http://localhost:4001/admin/ also serves the admin UI, but (for example) the image references don't work there. i'm just saying that because I'd be inclined to remove the static `/admin/` folder from the repository and show this one instead (maybe with a proxy) in the long run. having the admin interface publicly available .. doesn't sound like the best idea on earth

**Pull request merged**
